name: "Rebuild the JS"
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: Rebuild
        run: |
          npm install 
          npm run build:js
        
      - name: Upload Files
        uses: actions/upload-pages-artifact@v3
        with:
          path: |
            **/*  # 使用glob模式匹配所有文件和目录
            !.git/  # 排除.git目录